# Exercício 1 - Await a second!

Quando você tenta usar o `await` fora de uma função marcada como `async`, receberá um erro de sintaxe, pois o `await` só pode ser usado dentro de funções assíncronas/`async`, onde a execução assíncrona pode ser controlada de forma apropriada.